apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deploy
  labels:
    name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: server
  template:
    metadata:
      labels:
        name: server
    spec:
      containers:
        - name: my-container
          image: littelrepka/hello-drogon3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-deploy
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    name: server
  ports:
    - name: server-deploy-service-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
